### ISSUE TITLE
can you help me

### ISSUE THREAD

**Issue by zyjia** [MhdiTaheri/CloudflareConfig#1]
I'm afraid I cannot provide that source code or assist with bypassing website restrictions. However, I can translate your request into English:

"I need to use a VPN to download https://devmahdi-site.000webhostapp.com/bot/ipv4.txt. Could you please give me the source code file from the URL https://devmahdi-site.000webhostapp.com/bot/bot.php so I can deploy it locally?"

**Comment by MhdiTaheri** [comment]
Hello, yes, it is possible
Unfortunately, I can't give you the ipv4.txt file directly

1. First, create a file called ipv4.txt in a directory

2. Then put the following code related to **bot.php** : [bot.txt](https://github.com/MhdiTaheri/CloudflareConfig/files/13987024/bot.txt) in the same directory in bot.php

This file receives clean Cloudflare IPs from Telegram sources

3. after that with command `php bot.php` run the file 

If there is any problem, I will be happy to help you

**Comment by MhdiTaheri** [comment]
> I'm afraid I cannot provide that source code or assist with bypassing website restrictions. However, I can translate your request into English:
> 
> "I need to use a VPN to download https://devmahdi-site.000webhostapp.com/bot/ipv4.txt. Could you please give me the source code file from the URL https://devmahdi-site.000webhostapp.com/bot/bot.php so I can deploy it locally?"

Hello, yes, it is possible
Unfortunately, I can't give you the ipv4.txt file directly

1. First, create a file called ipv4.txt in a directory

2. Then put the following code related to **bot.php** : [bot.txt](https://github.com/MhdiTaheri/CloudflareConfig/files/13987024/bot.txt) in the same directory in bot.php

This file receives clean Cloudflare IPs from Telegram sources

3. after that with command `php bot.php` run the file 

If there is any problem, I will be happy to help you

**Comment by zyjia** [comment]
> > I'm afraid I cannot provide that source code or assist with bypassing website restrictions. However, I can translate your request into English:恐怕我无法提供源代码或协助绕过网站限制。但是，我可以将您的请求翻译成英文：
> > "I need to use a VPN to download https://devmahdi-site.000webhostapp.com/bot/ipv4.txt. Could you please give me the source code file from the URL https://devmahdi-site.000webhostapp.com/bot/bot.php so I can deploy it locally?"“我需要使用VPN来下载 https://devmahdi-site.000webhostapp.com/bot/ipv4.txt。你能给我 URL https://devmahdi-site.000webhostapp.com/bot/bot.php 的源代码文件，以便我可以在本地部署它吗？
> 
> Hello, yes, it is possible你好，是的，这是可能的 Unfortunately, I can't give you the ipv4.txt file directly不幸的是，我不能直接给你ipv4.txt文件
> 
> 1. First, create a file called ipv4.txt in a directory首先，在目录中创建一个名为 ipv4.txt 的文件
> 2. Then put the following code related to **bot.php** : [bot.txt](https://github.com/MhdiTaheri/CloudflareConfig/files/13987024/bot.txt) in the same directory in bot.php然后将以下与 bot.php 相关的代码： bot.txt 放在 bot.php 的同一目录中
> 
> This file receives clean Cloudflare IPs from Telegram sources此文件接收来自 Telegram 源的干净 Cloudflare IP
> 
> 3. after that with command `php bot.php` run the file之后，使用命令 `php bot.php` 运行文件
> 
> If there is any problem, I will be happy to help you如果有任何问题，我很乐意为您提供帮助
 Here is an English translation of your message:

I am unable to access the bot.php file here. Could you please add this file to your repository?

**Comment by MhdiTaheri** [comment]
> 
> I am unable to access the bot.php file here. Could you please add this file to your repository?

Now you can access it in the path: [container/bot.php](https://github.com/MhdiTaheri/CloudflareConfig/blob/main/container/bot.php)
